### PR TITLE
Add Tapioca-BookingSync

### PR DESCRIPTION
**Pull request by ZenCocoon**

### CODE REVIEW

**Comment by filipeximenes** [comment]
Hi, thanks!
I'm not being able to pip install the wrapper. Did you upload it to pypi?

**Comment by ZenCocoon** [comment]
@PaoloC68 can you please shade some light about this please.

**Comment by ZenCocoon** [comment]
@PaoloC68 any news on this?

**Comment by PaoloC68** [comment]
@filipeximenes I have fixed it, submitted to https://pypi.python.org/pypi/tapioca-bookingsync

**Comment by ZenCocoon** [comment]
@PaoloC68 Awesome, thanks a lot :) :tada:

**Comment by filipeximenes** [comment]
I'm not sure what is going on but I still cannot download your package.
I can see in pypi it has a "Download URL" witch i don't think is the normal way to upload a package. You are supposed to have uploaded the .tar.gz to pypi. 
Here you can compare the difference between your package and one i've published:
https://pypi.python.org/pypi/tapioca-bookingsync
https://pypi.python.org/pypi/tapioca-facebook

Did you run ``python setup.py register`` in the root of the project? This runs a script to generate a pypi ready package and registers it. To upload new versions, change the "\__version\__" variable in ``tapioca_bookingsync/__init__.py`` and run ``python setup.py publish``

**Comment by fjsj** [comment]
Closing due to inactivity. Please feel free to reply here and we can re-open.

**Pull request closed without merging**
