### PR TITLE
Add CrunchBase to flavours

### PR DESCRIPTION
**Pull request by vu3jej**
Adding CrunchBase to the list of flavours!

### CODE REVIEW

**Comment by vu3jej** [comment]
Seems like I deleted the newline at the end of the page accidentally and failed to notice it while doing `git diff`. I can resubmit the PR if needed.

**Comment by filipeximenes** [comment]
Thanks! Just update the PR :)

Also, It needs to be PyPI so people can install using pip.
I need to find some time to document the whole process of creating new wrappers =/

**Comment by vu3jej** [comment]
Submitted a new pull request! The whole thing was confusing the first time around. I've uploaded the package to PyPI also. I'm sorry if it was too much trouble.

**Comment by vu3jej** [comment]
I have reopened the PR at #57

**Comment by vu3jej** [comment]
I have added the PR here #57

**Pull request closed without merging**
