### PR TITLE
add tapioca-github to flavours

### PR DESCRIPTION
**Pull request by romulocollopy**

### CODE REVIEW

**Comment by filipeximenes** [comment]
Can you fix the conflicts?

**Comment by romulocollopy** [comment]
done!

**Comment by vu3jej** [comment]
I was about to start working on it today! Thanks for saving me some work :+1:

**Comment by filipeximenes** [comment]
Thanks!

Just note: this lib is tied to version "==0.4.1" of tapioca. 
Maybe update it to ">=0.6,<0.7" ;)

**Pull request merged**
